### ISSUE TITLE
Safeguard the backend against the last 2 facilitators being able to delete each other

### ISSUE THREAD

**Issue by achaikou** [equinor/fusion-bmt#512]
Looks like we have the following problem: not only facilitators can access the evaluation in Nomination stage, but everyone.

- If the person isn't added to evaluation, they need the direct link to access it. But then they are free to do anything with users.
- If the person is added to evaluation as participant, they already get the link to evaluation on their dashboard, thus can go directly into it and do any wicked things they want to.

Noticed during quick testing, so more related problems can actually exist.

**Comment by achaikou** [comment]
Additional problems. Not only participants have the power to remove facilitators (in remove facilitators version. In version where this PR is not merged people can remove themselves), but they also can assure they can't be removed at all.

I am added as a participant. I already have access to the evaluation. I go to Actions tab and create an action. Now no-one can remove me because my foreign key is now in the database,

**Comment by achaikou** [comment]
Note that due to browser cache we must have this disabled both in frontend and backed.
Example: two facilitators have their browsers opened. They remove each other. There are no facilitators left.
To prevent this check must be implemented in backend.

**Comment by ReedOnly** [comment]
Only Facilitator and Org Lead should be able to add and people to an evaluation

**Comment by ReedOnly** [comment]
Only Facilitator should be able to progress evaluation in all steps

**Comment by ErlendHaa** [comment]
### Status update

- [ ] Only Facilitator and Org Lead should be able to **add* and **delete**  and people to an evaluation (fixed in [#553](https://github.com/equinor/fusion-bmt/pull/553)) 

- [ ]  Only Facilitator should be able to progress evaluation in all steps (fixed in [#553](https://github.com/equinor/fusion-bmt/pull/553)) 

- [ ] Non-participants cannot interact with the evaluation (in nomination) (fixed in [#553](https://github.com/equinor/fusion-bmt/pull/553)) 

- [ ] Safeguard the backend against the last 2 facilitators being able to delete each other

**Comment by achaikou** [comment]
So existing changes are not done in backend, only in frontend? Why? Shouldn't that be a backend constraint first and foremost?
If we rely on frontend, we are dependent on not having bugs in frontend to make it work, and that's more difficult. Also we do not defend against malicious graphql queries from users. Not that anyone will likely do it, but without backend guard I, or anyone, will be able to send a graphql query directly to the server, do whatever, and no-one will know what happened as we probably don't even have good access logs.

That's why "2 facilitators can delete each other" still is a problem.
Nina noticed when we discussed the issue some time before, when I suggested we need to safeguard against it there, that if restrictions were implemented in backend, this situation would no longer be a problem, because when A removes B, B is no longer facilitator. So when B tries to remove A, this should be stopped by backend, because B simply shouldn't have privileges anymore to do anything in backend, as they are not facilitator.

**Comment by ErlendHaa** [comment]
> Why? Shouldn't that be a backend constraint first and foremost?

Because the _current_ design philosophy behind BMT is to let the backend completely open. Almost all restrictions we have are rooted in the frontend. The so-far implemented restrictions follow the same pattern.

Does that mean I agree with this _general_ design? Not necessarily. Should we have a proper discussion about it? Most def? But this was not the time nor the place... Here is what you are looking for: https://github.com/equinor/fusion-bmt/issues/537
